CREATE TABLE IF NOT EXISTS ps_endpoints (
    id varchar(40) PRIMARY KEY,
    transport varchar(40),
    aors varchar(200),
    auths varchar(200),
    outbound_auth varchar(40),
    context varchar(40),
    disallow varchar(200) DEFAULT 'all',
    allow varchar(200) DEFAULT 'ulaw,alaw',
    direct_media boolean DEFAULT true,
    rtp_symmetric boolean DEFAULT false,
    force_rport boolean DEFAULT false,
    rewrite_contact boolean DEFAULT false,
    trust_id_inbound boolean DEFAULT false,
    send_rpid varchar(11) DEFAULT 'no',
    mailboxes varchar(200),
    webrtc boolean DEFAULT false,
    use_avpf boolean DEFAULT false,
    dtls_verify varchar(10) DEFAULT 'yes',
    dtls_cert_file varchar(255),
    dtls_private_key varchar(255),
    dtls_setup varchar(8) DEFAULT 'actpass',
    dtls_fingerprint varchar(10) DEFAULT 'sha-256',
    media_encryption varchar(9) DEFAULT 'no',
    timers boolean DEFAULT true,
    timers_min_se integer DEFAULT 90,
    timers_sess_expires integer DEFAULT 1800,
    allow_subscribe boolean DEFAULT false,
    allow_overlapping boolean DEFAULT true,
    allow_transfer boolean DEFAULT true
);
