[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[endpoint-template](!)
type = endpoint
context = default
disallow = all
allow = ulaw,alaw
direct_media = no
rtp_timeout = 30
send_pai = yes

[alice](endpoint-template)
auth = alice
aors = alice

[alice]
type = auth
auth_type = userpass
password = alice
username = alice

[alice]
type = aor
contact = sip:alice@127.0.0.1:5060

[bob](endpoint-template)
auth = bob
aors = bob

[bob]
type = auth
auth_type = userpass
password = bob
username = bob

[bob]
type = aor
contact = sip:bob@127.0.0.1:5060