/**
 * Create IVR Flow Use Case
 * 
 * Validates and creates a new IVR flow
 */

import { Injectable, Inject, ConflictException, BadRequestException } from '@nestjs/common';
import { IVRFlowRepositoryPort } from '../ports/ivr-flow-repository.port';
import { IVRFlow, IVRFlowStatus } from '../domain/ivr-flow.domain';

@Injectable()
export class CreateFlowUseCase {
  constructor(
    @Inject('IVR_FLOW_REPOSITORY')
    private readonly flowRepository: IVRFlowRepositoryPort,
  ) {}

  async execute(params: {
    name: string;
    description?: string;
    organizationId: string;
    nodes: any[];
    entryNodeId: string;
    variables?: Record<string, any>;
  }): Promise<IVRFlow> {
    // Check for name uniqueness
    const existing = await this.flowRepository.existsByName(
      params.organizationId,
      params.name,
    );

    if (existing) {
      throw new ConflictException(`IVR flow with name '${params.name}' already exists`);
    }

    // Create domain object
    const flow = new IVRFlow({
      id: '', // Generated by repo
      name: params.name,
      description: params.description,
      organizationId: params.organizationId,
      status: IVRFlowStatus.DRAFT,
      nodes: params.nodes,
      entryNodeId: params.entryNodeId,
      variables: params.variables || {},
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    // Validate flow
    const validation = flow.validate();
    if (!validation.valid) {
      throw new BadRequestException({
        message: 'Invalid IVR flow',
        errors: validation.errors,
      });
    }

    // Save
    return await this.flowRepository.create(flow);
  }
}
