[sip2sip-reg]
type=registration
transport=transport-tls
outbound_auth=sip2sip-auth
server_uri=sip:2way.ipcomms.net:5061
client_uri=sip:manimaran@2way.ipcomms.net
contact=sip:manimaran@2way.ipcomms.net:5061;transport=TLS
retry_interval=60
auth_rejection_permanent=false

[sip2sip-auth]
type=auth
auth_type=userpass
username=manimaran
password=Amarancse@27

[sip2sip-aor]
type=aor
qualify_frequency=60

[sip2sip-trunk]
type=endpoint
transport=transport-tls
context=from-sip2sip
disallow=all
allow=ulaw,alaw,gsm,opus
outbound_auth=sip2sip-auth
auth=sip2sip-auth
aors=sip2sip-aor
from_user=manimaran
from_domain=2way.ipcomms.net
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
