#!/bin/bash
# PostgreSQL Replica Initialization Script
# Phase 1 Infrastructure - Streaming Replication Setup
# Psitrix Psynq CPaaS Platform

set -e

echo "========================================="
echo "PostgreSQL Replica Initialization"
echo "========================================="

# Environment Variables
PRIMARY_HOST="${POSTGRES_PRIMARY_HOST:-postgres_primary}"
PRIMARY_PORT="${POSTGRES_PRIMARY_PORT:-5432}"
REPLICATION_USER="${POSTGRES_REPLICATION_USER:-replicator}"
REPLICATION_PASSWORD_FILE="${POSTGRES_REPLICATION_PASSWORD_FILE:-/run/secrets/postgres_password}"
DATA_DIR="/var/lib/postgresql/data"

# Read replication password from secret
if [ -f "$REPLICATION_PASSWORD_FILE" ]; then
    REPLICATION_PASSWORD=$(cat "$REPLICATION_PASSWORD_FILE")
else
    echo "ERROR: Replication password file not found at $REPLICATION_PASSWORD_FILE"
    exit 1
fi

# Check if data directory is already initialized
if [ -s "$DATA_DIR/PG_VERSION" ]; then
    echo "Data directory already initialized. Checking if it's a replica..."
    
    if [ -f "$DATA_DIR/standby.signal" ]; then
        echo "Already configured as standby. Starting normally."
        exec postgres
    else
        echo "WARNING: Data directory exists but is not a replica."
        echo "To reinitialize as replica, remove the data directory and restart."
        exec postgres
    fi
fi

echo "Data directory is empty. Initializing replica..."

# Wait for primary to be ready
echo "Waiting for primary server at $PRIMARY_HOST:$PRIMARY_PORT..."
until pg_isready -h "$PRIMARY_HOST" -p "$PRIMARY_PORT" -U "$REPLICATION_USER" 2>/dev/null; do
    echo "Primary server is unavailable - sleeping"
    sleep 5
done

echo "Primary server is ready. Starting base backup..."

# Perform base backup from primary
PGPASSWORD="$REPLICATION_PASSWORD" pg_basebackup \
    -h "$PRIMARY_HOST" \
    -p "$PRIMARY_PORT" \
    -U "$REPLICATION_USER" \
    -D "$DATA_DIR" \
    -Fp \
    -Xs \
    -P \
    -R

if [ $? -eq 0 ]; then
    echo "Base backup completed successfully."
else
    echo "ERROR: Base backup failed."
    exit 1
fi

# Create standby.signal file (marks this as a replica)
touch "$DATA_DIR/standby.signal"

# Configure postgresql.auto.conf for replication settings
cat >> "$DATA_DIR/postgresql.auto.conf" <<EOF
# Streaming Replication Configuration
# Generated by replica initialization script

primary_conninfo = 'host=$PRIMARY_HOST port=$PRIMARY_PORT user=$REPLICATION_USER password=$REPLICATION_PASSWORD application_name=psynq_postgres_replica'
primary_slot_name = 'replica_slot'
hot_standby = on
hot_standby_feedback = on
max_standby_streaming_delay = 30s
wal_receiver_status_interval = 10s
wal_retrieve_retry_interval = 5s
EOF

echo "Replication configuration written to postgresql.auto.conf"

# Set correct permissions
chown -R postgres:postgres "$DATA_DIR"
chmod 0700 "$DATA_DIR"

echo "========================================="
echo "Replica initialization completed!"
echo "Starting PostgreSQL in hot standby mode..."
echo "========================================="

# Start PostgreSQL
exec postgres
