[settings]
ps_globals => odbc,psynq,ps_globals
extensions => odbc,psynq,extensions
ps_endpoints => odbc,psynq,ps_endpoints
ps_registrations => odbc,psynq,ps_registrations
ps_identifies => odbc,psynq,ps_identifies
ps_auths => odbc,psynq,ps_auths
ps_aors => odbc,psynq,ps_aors
ps_contacts => odbc,psynq,ps_contacts
ps_domain_aliases => odbc,psynq,ps_domain_aliases
ps_endpoint_id_ips => odbc,psynq,ps_endpoint_id_ips
realtime_trim_whitespace => yes
