; Music on Hold Configuration
; This defines different music on hold classes for different situations

[default]
mode=files
directory=moh
random=yes
; Default music on hold

[queue]
mode=files
directory=moh/queue
random=yes
; Music for callers in queue

[silence]
mode=files
directory=moh/silence
random=no
; Silent "music" for when we need to mute participants