#!/usr/bin/env pwsh
# Twilio SIP Trunk Configuration Script
# This script helps you configure Twilio SIP trunking with Asterisk

Write-Host "====================================" -ForegroundColor Cyan
Write-Host "  Twilio SIP Trunk Setup Script" -ForegroundColor Cyan
Write-Host "  for Psynq Asterisk Integration" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host ""

# Check if Asterisk is running
$asteriskRunning = docker ps --filter "name=psynq-asterisk" --format "{{.Names}}" | Select-String "psynq-asterisk"
if (-not $asteriskRunning) {
    Write-Host "❌ Asterisk container is not running!" -ForegroundColor Red
    Write-Host "Please start Asterisk first: docker-compose up -d asterisk" -ForegroundColor Yellow
    exit 1
}

Write-Host "✅ Asterisk container is running" -ForegroundColor Green
Write-Host ""

# Display instructions
Write-Host "📋 BEFORE YOU CONTINUE, you need:" -ForegroundColor Yellow
Write-Host "1. Twilio account (free trial works!)" -ForegroundColor White
Write-Host "2. Your mobile number VERIFIED in Twilio Console" -ForegroundColor White
Write-Host "3. A Twilio SIP Trunk created" -ForegroundColor White
Write-Host "4. A Credential List with username/password" -ForegroundColor White
Write-Host "5. Your public IP added to IP Access Control List" -ForegroundColor White
Write-Host ""
Write-Host "📚 Full setup guide: scripts/twilio-setup.md" -ForegroundColor Cyan
Write-Host ""

$continue = Read-Host "Have you completed these steps? (y/n)"
if ($continue -ne "y") {
    Write-Host "Please complete the setup steps first. See: scripts/twilio-setup.md" -ForegroundColor Yellow
    exit 0
}

# Get configuration from user
Write-Host ""
Write-Host "🔧 Configuration" -ForegroundColor Cyan
Write-Host "================" -ForegroundColor Cyan

$sipDomain = Read-Host "Enter your Twilio SIP Domain (e.g., TKxxxxx.pstn.twilio.com)"
$username = Read-Host "Enter your Credential List username (e.g., psynq-user)"
$password = Read-Host "Enter your Credential List password" -AsSecureString
$passwordPlain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($password))

$confirm = Read-Host "Configure Twilio trunk with these settings? (y/n)"
if ($confirm -ne "y") {
    Write-Host "Configuration cancelled." -ForegroundColor Yellow
    exit 0
}

# Backup existing config
$configFile = "deploy/asterisk/asterisk-config/pjsip.d/twilio-trunk.conf"
if (Test-Path $configFile) {
    $backupFile = "$configFile.backup"
    Copy-Item $configFile $backupFile
    Write-Host "✅ Backed up existing config to: $backupFile" -ForegroundColor Green
}

# Create new configuration
$twilioConfig = @"
; Twilio SIP Trunk Configuration for Free Trial Account
; Auto-generated by setup-twilio.ps1

[twilio-trunk]
type=endpoint
transport=transport-udp
context=from-twilio
disallow=all
allow=ulaw,alaw
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
from_domain=$sipDomain

[twilio-auth]
type=auth
auth_type=userpass
username=$username
password=$passwordPlain

[twilio-aor]
type=aor
contact=sip:$sipDomain
qualify_frequency=60
qualify_timeout=5

[twilio-identify]
type=identify
endpoint=twilio-trunk
match=$sipDomain

[twilio-registration]
type=registration
transport=transport-udp
outbound_auth=twilio-auth
server_uri=sip:$sipDomain
client_uri=sip:$username@$sipDomain
retry_interval=60
forbidden_retry_interval=300
auth_rejection_permanent=false
line=no
endpoint=twilio-trunk
"@

# Write configuration file
$twilioConfig | Out-File -FilePath $configFile -Encoding ASCII
Write-Host "✅ Configuration file updated: $configFile" -ForegroundColor Green

# Set as default trunk in extensions.conf
$extensionsFile = "deploy/asterisk/asterisk-config/extensions.conf"
$extensionsContent = Get-Content $extensionsFile -Raw
$extensionsContent = $extensionsContent -replace 'DEFAULT_TRUNK=\w+', 'DEFAULT_TRUNK=twilio'
$extensionsContent | Out-File -FilePath $extensionsFile -Encoding ASCII
Write-Host "✅ Updated extensions.conf to use Twilio as default trunk" -ForegroundColor Green

# Restart Asterisk
Write-Host ""
Write-Host "🔄 Restarting Asterisk..." -ForegroundColor Cyan
docker restart psynq-asterisk | Out-Null
Start-Sleep -Seconds 5

# Check registration status
Write-Host ""
Write-Host "🔍 Checking registration status..." -ForegroundColor Cyan
$registration = docker exec psynq-asterisk asterisk -rx "pjsip show registrations" 2>&1

if ($registration -match "Registered") {
    Write-Host "✅ SUCCESS! Twilio SIP trunk is registered!" -ForegroundColor Green
    Write-Host ""
    Write-Host "🎉 You can now make outbound calls to VERIFIED numbers!" -ForegroundColor Green
    Write-Host ""
    Write-Host "📞 Test a call:" -ForegroundColor Cyan
    Write-Host "   docker exec -it psynq-asterisk asterisk -rx `"channel originate PJSIP/+919876543210@twilio-trunk application echo`"" -ForegroundColor White
    Write-Host ""
    Write-Host "(Replace +919876543210 with YOUR VERIFIED mobile number)" -ForegroundColor Yellow
} else {
    Write-Host "❌ Registration failed!" -ForegroundColor Red
    Write-Host ""
    Write-Host "Debug info:" -ForegroundColor Yellow
    Write-Host $registration
    Write-Host ""
    Write-Host "Troubleshooting:" -ForegroundColor Yellow
    Write-Host "1. Check your credentials in Twilio Console" -ForegroundColor White
    Write-Host "2. Verify your public IP is in the IP Access Control List" -ForegroundColor White
    Write-Host "3. Enable SIP debugging: docker exec -it psynq-asterisk asterisk -rx 'pjsip set logger on'" -ForegroundColor White
    Write-Host "4. Check logs: docker logs psynq-asterisk" -ForegroundColor White
    Write-Host ""
    Write-Host "📚 Full troubleshooting guide: scripts/twilio-setup.md" -ForegroundColor Cyan
}

Write-Host ""
Write-Host "✨ Setup complete!" -ForegroundColor Cyan
